import { NgModule } from '@angular/core';

import {
    MatButtonModule,
    MatGridListModule,
    MatListModule,
    MatDividerModule,
    MatCardModule,
    MatMenuModule,
    MatDialogModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatInputModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatBadgeModule,
    MatToolbarModule,
    MatSliderModule,
    MatTableModule,
    MatTreeModule,
    MatRadioModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatTabsModule,
    MatTooltipModule,
 } from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatGridListModule,
    MatListModule,
    MatDividerModule,
    MatCardModule,
    MatMenuModule,
    MatDialogModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatInputModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatBadgeModule,
    MatToolbarModule,
    MatSliderModule,
    MatTableModule,
    MatTreeModule,
    MatIconModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatProgressBarModule,
    MatTabsModule,
    MatTooltipModule,
  ],
  exports: [
    MatButtonModule,
    MatGridListModule,
    MatListModule,
    MatDividerModule,
    MatCardModule,
    MatMenuModule,
    MatDialogModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatInputModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatBadgeModule,
    MatToolbarModule,
    MatSliderModule,
    MatRadioModule,
    MatTableModule,
    MatTreeModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatProgressBarModule,
    MatTabsModule,
    MatTooltipModule,
  ]
})
export class MaterialModule {}
